# Site settings
title: Efren's Personal Site
email: your-email@example.com
description: >-
  Welcome to my personal website. Here you'll find my thoughts, projects,
  and anything else I'd like to share with the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://efrenbl.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter_username
github_username: efrenbl

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Efren"
  - scope:
      path: ""
    values:
      layout: "default"

# Pagination
paginate: 5
paginate_path: "/page:num/"
