# Site settings
title: efren.dev
email: efrenbl@proton.me
description: >-
  Staff Machine Learning Engineer, IEEE Volunteer, and Career Coach 
  specializing in MLOps, cloud architecture, and engineering leadership.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://efrenbl.github.io" # the base hostname & protocol for your site
linkedin_username: efrenbl
github_username: efrenbl

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages safe plugins only
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Efren"
  - scope:
      path: ""
    values:
      layout: "default"

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Navigation
header_pages:
  - blog.md
  - about.md
  - projects.md
  - experience.md
